<?php

namespace OC\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends EntityRepository
{
	public function getApplicationsWithAdvert($limit){
		$qb = $this->createQueryBuilder('a')
				->leftjoin('a.advert', 'adv')
				->addselect('adv');

		$qb->setMaxResults($limit);

		return $qb
      		->getQuery()
     		->getResult();
	}

	public function isFlood(){
		return false;
	}
}
